# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: python environment
          command: python3 -m venv venv; . venv/bin/activate
      - run:
          name: install dependencies
          command: . venv/bin/activate; make install
      - run:
          name: install pylint
          command: . venv/bin/activate; pip install pylint --user
      - run:
          name: install hadolint
          command: wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && chmod +x /bin/hadolint
      - run:
          name: run lint
          command: . venv/bin/activate; make lint 
